### ISSUE TITLE
Tareas - Osvaldo

### ISSUE THREAD

**Issue by CaroCarcamo** [CaroCarcamo/ProyectoIntegradorISPC#9]
Desde la consola de Git:

Clonal el repositorio remoto grupal (https://github.com/CaroCarcamo/ProyectoIntegradorISPC)
Crear rama personal en el disco local
Switchearse (moverse) a la rama personal
Agregar Curriculum Vitae en formato pdf a la rama personal
Subir la rama personal, al repositorio remoto grupal

**Comment by Metalderly** [comment]
Tarea terminada, no es waaaaaau que cv pero cumple con las expectativas:)
